In [28]:
import numpy as np
from codingChallenge import utils
import psutil
from threading import Thread
import threading


class MedianCalculator(object):
    """
    Class used to abstract the calculation of the median
    """
    def __init__(self, tweet_input):
        self.tweet_iterable = []
        # Handle the edge case where a single tweet is supplied as a string,
        # not an array iterable
        if type(tweet_input) == str:
            self.tweet_iterable = [tweet_input]
        else:
            self.tweet_iterable = tweet_input
        self.num_unique_words_sorted = []
        self.median_list = []

    def format_to_two_decimal(self, input_amount):
        formatted_string = "{0:.2f}".format(input_amount)
        return float(formatted_string)

    def append_to_unique_word_list(self, tweet):
        tweet_unique_words = len(set(tweet.split()))
        self.num_unique_words_sorted.append(tweet_unique_words)
        self.num_unique_words_sorted = sorted(self.num_unique_words_sorted)

    def populate_median_list(self):
        for dirty_tweet in self.tweet_iterable:
            tweet = utils.clean_tweet(dirty_tweet)
            self.append_to_unique_word_list(tweet)
            current_number_of_tweets = len(self.num_unique_words_sorted)
            # Condition if odd amount
            if current_number_of_tweets % 2:
                index = current_number_of_tweets / 2
                self.median_list.append(self.num_unique_words_sorted[index])
            # Condition if even amount
            else:
                left_index = (current_number_of_tweets / 2) - 1
                right_index = current_number_of_tweets / 2

                average_of_medians = self.format_to_two_decimal(
                    (self.num_unique_words_sorted[left_index] +
                     self.num_unique_words_sorted[right_index]) / 2.0)
                self.median_list.append(average_of_medians)

        return self.median_list

    def numpy_calculate_median(self):
        tweet_array = np.genfromtxt(self.tweet_iterable, dtype=np.string_,
                                    comments=False, delimiter="\n")
        tweet_bag_of_words = np.array([tweet.split() for tweet in tweet_array])
        running_list_of_uniques = []
        running_list_of_median = []
        for tweet in tweet_bag_of_words:
            filtered_tweet = (np.unique(tweet))
            running_list_of_uniques.append(len(filtered_tweet))
            running_list_of_median.append(np.median(running_list_of_uniques))
        return running_list_of_median

    def run(self):
        """
        Run methods necessary to return the array of medians.

        The run method helps abstract away the calling of the methods so that
        less refacotring is needed later on.
        """
        return self.numpy_calculate_median()






In [229]:
test_tweets = [
        "is #bigdata finally the answer to end poverty? \
        @lavanyarathnam http://ow.ly/o8gt3 #analytics",
        "interview: xia wang, astrazeneca on #bigdata and the promise of effective \
        healthcare #kdn http://ow.ly/ot2uj",
        "big data is not just for big business. on how #bigdata is being deployed for \
        small businesses: http://bddy.me/1bzukb3 @cxotodayalerts #smb"
    ]

In [8]:
psutil.cpu_count()

8

In [51]:
# a = np.array([1,2,3,4])
# np.array_split(a,psutil.cpu_count())
thread_list = []
a = np.array(range(100000))
b = np.empty(0)

lock = threading.Lock()
NUM_CORES = psutil.cpu_count()

def worker(test, lock):
    global b
    space = np.median(test)
    with lock:
        b = np.append(b, space)
    
for number, split in enumerate(np.array_split(a, NUM_CORES)):
    print split
    t = Thread(target=worker, args=(split,lock,))
    thread_list.append(t)
    t.start()
for x in thread_list:
    x.join()
print b

[    0     1     2 ..., 12497 12498 12499]
[12500 12501 12502 ..., 24997 24998 24999]
[25000 25001 25002 ..., 37497 37498 37499]
[37500 37501 37502 ..., 49997 49998 49999]
[50000 50001 50002 ..., 62497 62498 62499]
[62500 62501 62502 ..., 74997 74998 74999]
[75000 75001 75002 ..., 87497 87498 87499]
[87500 87501 87502 ..., 99997 99998 99999]
[  6249.5  18749.5  31249.5  43749.5  56249.5  68749.5  81249.5  93749.5]


In [231]:
def distributed_numpy_count_unique(self):
    tweet_array = np.genfromtxt(self.tweet_iterable, dtype=np.string_,
                                comments=False, delimiter="\n")
    word_array = np.concatenate([tweet.split() for tweet in tweet_array])
    word_count = Counter(word_array)
    alphabetized_count = OrderedDict(sorted(word_count.items(), key=itemgetter(0)))
    return alphabetized_count.items()

['is #bigdata finally the answer to end poverty?         @lavanyarathnam http://ow.ly/o8gt3 #analytics',
 'interview: xia wang, astrazeneca on #bigdata and the promise of effective         healthcare #kdn http://ow.ly/ot2uj']

In [247]:
def numpy_calculate_median(self):
        tweet_array = np.genfromtxt(self, dtype=np.string_,
                                    comments=False, delimiter="\n")
        tweet_bag_of_words = np.array([tweet.split() for tweet in tweet_array])
        running_list_of_uniques = np.empty(0)
        running_list_of_median = np.empty(0)
        for tweet in tweet_bag_of_words:
            filtered_tweet_length = np.unique(tweet).size
            running_list_of_uniques = np.append(running_list_of_uniques, filtered_tweet_length)
            running_list_of_median = np.append(running_list_of_median, np.median(running_list_of_uniques))
        return running_list_of_median

In [248]:
a = numpy_calculate_median(test_tweets)

In [249]:
a

array([ 11. ,  12.5,  14. ])

array([ 14. ,  12.5,  11. ])

In [242]:
a = np.array([4,5,6,8])
a = np.append(a,[1])
print a

[4 5 6 8 1]


In [60]:
def test_func(tweet_input):
    if type(tweet_input == str):
        return [tweet_input]
    else:
        return tweet_input

In [62]:
test_func(test_tweets[0:2])

[['is #bigdata finally the answer to end poverty?         @lavanyarathnam http://ow.ly/o8gt3 #analytics',
  'interview: xia wang, astrazeneca on #bigdata and the promise of effective         healthcare #kdn http://ow.ly/ot2uj']]

In [63]:
test_tweets[0:2]

['is #bigdata finally the answer to end poverty?         @lavanyarathnam http://ow.ly/o8gt3 #analytics',
 'interview: xia wang, astrazeneca on #bigdata and the promise of effective         healthcare #kdn http://ow.ly/ot2uj']

In [66]:
type(test_tweets[0:2]) == str

False